"""Character generation schemas."""

from __future__ import annotations

from dataclasses import dataclass

from beanie import PydanticObjectId  # noqa: TC002
from litestar.plugins.pydantic import PydanticDTO
from pydantic import BaseModel

from vapi.constants import CharacterClass, CharacterType  # noqa: TC001
from vapi.db.models.chargen_session import ChargenSession
from vapi.domain.handlers.character_autogeneration.constants import (
    AbilityFocus,  # noqa: TC001
    AutoGenExperienceLevel,  # noqa: TC001
)
from vapi.lib.dto import dto_config


class ChargenSessionFinalizeDTO(BaseModel):
    """Input DTO for finalizing character selection."""

    session_id: PydanticObjectId
    selected_character_id: PydanticObjectId


class ChargenSessionResponseDTO(PydanticDTO[ChargenSession]):
    """Chargen session response DTO."""

    config = dto_config(exclude={"company_id"})


@dataclass
class CreateAutogenerateDTO:
    """Create autogenerate DTO."""

    character_type: CharacterType
    character_class: CharacterClass | None = None
    experience_level: AutoGenExperienceLevel | None = None
    skill_focus: AbilityFocus | None = None
    concept_id: PydanticObjectId | None = None
    vampire_clan_id: PydanticObjectId | None = None
    werewolf_tribe_id: PydanticObjectId | None = None
    werewolf_auspice_id: PydanticObjectId | None = None
