"""Character generation schemas."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime  # noqa: TC003
from uuid import UUID  # noqa: TC003

from beanie import PydanticObjectId  # noqa: TC002
from pydantic import BaseModel

from vapi.constants import CharacterClass, CharacterType  # noqa: TC001
from vapi.db.models.character import Character  # noqa: TC001
from vapi.domain.handlers.character_autogeneration.constants import (
    AbilityFocus,  # noqa: TC001
    AutoGenExperienceLevel,  # noqa: TC001
)


class ChargenSessionResponse(BaseModel):
    """Response containing generated character options."""

    session_id: UUID
    expires_at: datetime
    requires_selection: bool
    characters: list[Character]


class ChargenSessionFinalizeDTO(BaseModel):
    """Input DTO for finalizing character selection."""

    session_id: UUID
    selected_character_id: PydanticObjectId


@dataclass
class CreateAutogenerateDTO:
    """Create autogenerate DTO."""

    character_type: CharacterType
    character_class: CharacterClass | None = None
    experience_level: AutoGenExperienceLevel | None = None
    skill_focus: AbilityFocus | None = None
    concept_id: PydanticObjectId | None = None
    vampire_clan_id: PydanticObjectId | None = None
    werewolf_tribe_id: PydanticObjectId | None = None
    werewolf_auspice_id: PydanticObjectId | None = None
