---
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
        informational: true
    patch:
      default:
        target: 75%
        threshold: 0%
        informational: true
  ignore:
    - tests/
    - scripts/
    - docs/
    - duties.py

comment:
  layout: "diff, flags, files, components"
  require_changes: false
