---
coverage:
  status:
    project:
      default:
        target: 25% # the required coverage value
        threshold: 5% # the leniency in hitting the target
    patch:
      default:
        target: 50%
        threshold: 5%
  ignore:
    - tests/
    - scripts/
    - docs/
    - duties.py

comment:
  layout: "diff, flags, files, components" # Remove items here to change the format
  require_changes: false
