---
services:
  api:
    build: .
    hostname: vapi
    container_name: vapi
    env_file:
      - .env.secret
    environment:
      - VAPI_REDIS__URL=redis://:redispassword@redis:6379/0
      - VAPI_POSTGRES__HOST=postgres
      - VAPI_POSTGRES__PORT=5432
      - VAPI_POSTGRES__USER=valentina
      - VAPI_POSTGRES__PASSWORD=valentina
      - VAPI_POSTGRES__DATABASE=valentina-noir
    volumes:
      - .dev:/app/.dev
    depends_on:
      - redis
      - postgres
    ports:
      - 8000:8000
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./uv.lock
          target: /app/uv.lock
        - action: rebuild
          path: ./pyproject.toml
          target: /app/pyproject.toml
        - action: rebuild
          path: ./Dockerfile

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass redispassword
    volumes:
      - .dev/redis:/data
    attach: false # suppress logs to console

  postgres:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: valentina
      POSTGRES_PASSWORD: valentina
      POSTGRES_DB: valentina-noir
    volumes:
      - .dev/postgres:/var/lib/postgresql/data
    attach: false # suppress logs to console
